project_id = "bpnzpiileyneehtihivc"

[functions.send-invitation-email]
verify_jwt = false

[functions.resend-invitation-email]
verify_jwt = true

[functions.test-smtp-connection]
verify_jwt = false

[functions.create-user-admin]
verify_jwt = true

[functions.delete-user-admin]
verify_jwt = true

[functions.submit-user-responses]
verify_jwt = true

[functions.bulk-create-users]
verify_jwt = true
