project_id = "bpnzpiileyneehtihivc"

[functions.send-invitation-email]
verify_jwt = false

[functions.resend-invitation-email]
verify_jwt = true

[functions.test-smtp-connection]
verify_jwt = false

[functions.create-user-admin]
verify_jwt = true

[functions.delete-user-admin]
verify_jwt = true

[functions.submit-user-responses]
verify_jwt = true

[functions.bulk-create-users]
verify_jwt = true

[functions.bulk-delete-users]
verify_jwt = true

[functions.bulk-resend-invitations]
verify_jwt = true

[functions.update-user-access]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true
